// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy6W256cdJnRHQFdKvqOhX8RPdftCAc18',
    appId: '1:435719764446:web:4dde27624af9b149ce854f',
    messagingSenderId: '435719764446',
    projectId: 'my-notes-4938c',
    authDomain: 'my-notes-4938c.firebaseapp.com',
    storageBucket: 'my-notes-4938c.appspot.com',
    measurementId: 'G-C2Z27XL3H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYdHnl0dfiJBUgoFUwhfoqrnixklE6rYE',
    appId: '1:435719764446:android:d7bbbbc75c6d534ece854f',
    messagingSenderId: '435719764446',
    projectId: 'my-notes-4938c',
    storageBucket: 'my-notes-4938c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr896sT-Jtd4srkPymtsJvf4wU3xk1Yi4',
    appId: '1:435719764446:ios:6fd043f4b248928cce854f',
    messagingSenderId: '435719764446',
    projectId: 'my-notes-4938c',
    storageBucket: 'my-notes-4938c.appspot.com',
    iosClientId: '435719764446-k8d0ahtrugmf2b58jnshehpihkm4hegq.apps.googleusercontent.com',
    iosBundleId: 'com.gideonDaniels.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr896sT-Jtd4srkPymtsJvf4wU3xk1Yi4',
    appId: '1:435719764446:ios:6fd043f4b248928cce854f',
    messagingSenderId: '435719764446',
    projectId: 'my-notes-4938c',
    storageBucket: 'my-notes-4938c.appspot.com',
    iosClientId: '435719764446-k8d0ahtrugmf2b58jnshehpihkm4hegq.apps.googleusercontent.com',
    iosBundleId: 'com.gideonDaniels.mynotes',
  );
}
